name: flutter_app
description: A simple Flutter crop yield prediction app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0

flutter:
  uses-material-design: true
